// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */

const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [

    {
      type: "category",
      label: "Catalog",
      link: { type: "doc", id: "catalog/intro" },
      items: [
        "catalog/arcade",
        "catalog/brainclip",
        "catalog/brainpower",
        {
          type: "category",
          label: "BrainPad Pulse",
          link: { type: "doc", id: "catalog/pulse" },
          items: [
            "catalog/brainsense",
            "catalog/brainbot",
            "catalog/braingamer",
            "catalog/braintronics",
          ],
        },
        "catalog/legacy",
      ],
    },
    {
      type: "category",
      label: "Resources",
      link: { type: "doc", id: "resources/intro" },
      items: [
        {
          type: "category",
          label: "MakeCode Arcade",
          link: { type: "doc", id: "resources/makecode-arcade" },
          items: [
            "resources/lessons/2d-adventure",
            "resources/lessons/space-shooter",
            "resources/lessons/edge-pads",
            "resources/lessons/analog-vs-digital",
            "resources/lessons/led-ring",
            "resources/lessons/motion-sense",
            "resources/lessons/light-sense",
            "resources/lessons/sound-sense",
          ],
        },
        //"resources/python",
        //"resources/javascript",
        //"resources/duelink",
        "resources/makecode",
      ],
    },
    "support",
    "legal",
    "safety",
  ],
};

export default sidebars;
